### ISSUE TITLE
OneSignal

### ISSUE THREAD

**Issue by mluksenberg** [Shippear/core#86]
Voy a necesitar que desde back envien lo siguiente:
{"app_id": "ID_ONE_SIGNAL",
          "contents": {"en": "MENSAJE_AL_DESTINATARIO"},
 "include_player_ids": ["ID_DESTINATARIO"],
 "data":{"order_id":"UNA_ORDER_ID", "new_state":"ORDER_STATE"}
}
Les explico, eso es lo que tienen que poner como body (modificando segun sea la ocación) al ONeSignal
Necesito que me envien el data
porque así actualizo la info en el celu

**Comment by nazarenolevy** [comment]
Agregar tambien el QR
